### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by flpfar** [Zubenna/my_telegram_bot#3]
Great job so far, Nnamdi!

- Try to think in a way to not call bot.listen more than one time
- Think about return only one message with several lines instead of several messages, it would avoid repeating code.
- You can write a test to check if your bot is being created, expecting it to be type of Telegram::Bot::Client
- You can get rid of instance variables inside your bot initialization.
- It would be a good practice to omit your keys from github.

Keep the great job!

**Comment by Zubenna** [comment]
Implemented
